# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on: [push, pull_request]

jobs:
  android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '9.0.4' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: Intall expo
        run: sudo npm i -g expo-cli
      - name: Install deps
        run: yarn install
      - name: Build Android APK Bundle
        run: expo build:android
  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '9.0.4' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: Intall expo
        run: sudo npm i -g expo-cli
      - name: Install deps
        run: yarn install
      - name: Build iOs
        run: expo build:ios
